name: fsanitize check test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_wolfssl:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        config: [
          # Add new configs here and make wolfclu matrix match
          '--enable-wolfclu',
          '--enable-wolfclu --enable-smallstack',
          '--enable-wolfclu --enable-experimental --enable-dilithium',
          '--enable-wolfclu --enable-smallstack --enable-experimental --enable-dilithium',
        ]
    name: Build wolfssl
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4
    steps:
      - name: Checking cache for wolfssl
        uses: actions/cache@v4
        id: cache-wolfssl
        with:
          path: build-dir/
          key: wolfclu-fsanitize-check-wolfssl-${{ strategy.job-index }}-${{ matrix.os }}
          lookup-only: true

      - name: Checkout, build, and install wolfssl
        if: steps.cache-wolfssl.outputs.cache-hit != 'true'
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: wolfssl/wolfssl
          ref: master
          path: wolfssl
          configure: ${{ matrix.config }} CC="gcc -fsanitize=address"
          check: false
          install: true

  build_wolfclu:
    needs: build_wolfssl
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        config: [
          '--enable-wolfclu',
          '--enable-wolfclu --enable-smallstack',
          '--enable-wolfclu --enable-experimental --enable-dilithium',
          '--enable-wolfclu --enable-smallstack --enable-experimental --enable-dilithium',
        ]
    name: Build wolfclu
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4
    steps:
      - name: Checking cache for wolfssl
        uses: actions/cache@v4
        with:
          path: build-dir/
          key: wolfclu-fsanitize-check-wolfssl-${{ strategy.job-index }}-${{ matrix.os }}
          fail-on-cache-miss: true

      - name: Checkout, build, and test wolfclu
        uses: wolfSSL/actions-build-autotools-project@v1
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/build-dir/lib
        with:
          repository: wolfssl/wolfclu
          path: wolfclu
          configure: CC="gcc -fsanitize=address" LDFLAGS="-L${{ github.workspace }}/build-dir/lib" CPPFLAGS="-I${{ github.workspace }}/build-dir/include"
          check: true
      - name: display log
        if: always()
        run: if [ -f test-suite.log ]; then cat test-suite.log; else echo "No test log"; fi
